package com.littlebridge.enrollplus.feature.ai

import com.littlebridge.enrollplus.feature.ai.NcertReferenceService.NcertChapter
import com.littlebridge.enrollplus.feature.ai.NcertReferenceService.NcertSyllabus
import com.littlebridge.enrollplus.feature.ai.NcertReferenceService.NcertTopic

/**
 * NCERT syllabus reference data — Part 1 (Class 6-9).
 * Source: NCERT official syllabus (ncert.nic.in)
 */
object NcertReferenceData {
    val DATA: List<NcertSyllabus> = listOf(

        // ════ CLASS 6 ════
        NcertSyllabus("Class 6", "Mathematics", listOf(
            NcertChapter("Knowing Our Numbers", listOf(NcertTopic("Comparing Numbers"), NcertTopic("Large Numbers"), NcertTopic("Estimation"))),
            NcertChapter("Whole Numbers", listOf(NcertTopic("Number Line"), NcertTopic("Properties of Whole Numbers"))),
            NcertChapter("Playing with Numbers", listOf(NcertTopic("Factors and Multiples"), NcertTopic("Prime and Composite"), NcertTopic("Divisibility Rules"))),
            NcertChapter("Basic Geometrical Ideas", listOf(NcertTopic("Points and Lines"), NcertTopic("Angles"), NcertTopic("Polygons"))),
            NcertChapter("Understanding Elementary Shapes", listOf(NcertTopic("Measuring Line Segments"), NcertTopic("Types of Angles"), NcertTopic("Triangles"))),
            NcertChapter("Integers", listOf(NcertTopic("Integers on Number Line"), NcertTopic("Addition of Integers"), NcertTopic("Subtraction of Integers"))),
            NcertChapter("Fractions", listOf(NcertTopic("Fraction on Number Line"), NcertTopic("Equivalent Fractions"), NcertTopic("Addition and Subtraction"))),
            NcertChapter("Decimals", listOf(NcertTopic("Tenths and Hundredths"), NcertTopic("Comparing Decimals"), NcertTopic("Addition and Subtraction"))),
            NcertChapter("Data Handling", listOf(NcertTopic("Recording Data"), NcertTopic("Pictograph"), NcertTopic("Bar Graph"))),
            NcertChapter("Mensuration", listOf(NcertTopic("Perimeter"), NcertTopic("Area"))),
            NcertChapter("Algebra", listOf(NcertTopic("Matchstick Patterns"), NcertTopic("Variables"), NcertTopic("Equations"))),
            NcertChapter("Ratio and Proportion", listOf(NcertTopic("Ratio"), NcertTopic("Proportion"), NcertTopic("Unitary Method"))),
            NcertChapter("Symmetry", listOf(NcertTopic("Line of Symmetry"), NcertTopic("Symmetrical Figures"))),
            NcertChapter("Practical Geometry", listOf(NcertTopic("Construction of Lines"), NcertTopic("Construction of Angles"))),
        )),

        NcertSyllabus("Class 6", "Science", listOf(
            NcertChapter("Food: Where Does It Come From?", listOf(NcertTopic("Food Variety"), NcertTopic("Food Sources"))),
            NcertChapter("Components of Food", listOf(NcertTopic("Nutrients"), NcertTopic("Balanced Diet"), NcertTopic("Deficiency Diseases"))),
            NcertChapter("Fibre to Fabric", listOf(NcertTopic("Natural Fibres"), NcertTopic("Plant Fibres"), NcertTopic("Animal Fibres"))),
            NcertChapter("Sorting Materials into Groups", listOf(NcertTopic("Objects Around Us"), NcertTopic("Properties of Materials"), NcertTopic("Classification"))),
            NcertChapter("Separation of Substances", listOf(NcertTopic("Methods of Separation"), NcertTopic("Filtration"), NcertTopic("Evaporation"))),
            NcertChapter("Changes Around Us", listOf(NcertTopic("Reversible and Irreversible Changes"), NcertTopic("Physical and Chemical Changes"))),
            NcertChapter("Getting to Know Plants", listOf(NcertTopic("Stem and Leaf"), NcertTopic("Roots"), NcertTopic("Flowers"))),
            NcertChapter("Body Movements", listOf(NcertTopic("Human Skeleton"), NcertTopic("Joints"), NcertTopic("Animal Movement"))),
            NcertChapter("The Living Organisms and Their Surroundings", listOf(NcertTopic("Habitat"), NcertTopic("Adaptations"), NcertTopic("Characteristics of Living Things"))),
            NcertChapter("Motion and Measurement of Distances", listOf(NcertTopic("Standard Units"), NcertTopic("Types of Motion"))),
            NcertChapter("Light, Shadows and Reflections", listOf(NcertTopic("Light"), NcertTopic("Shadows"), NcertTopic("Reflection"))),
            NcertChapter("Electricity and Circuits", listOf(NcertTopic("Electric Cell"), NcertTopic("Electric Circuit"), NcertTopic("Switch"))),
            NcertChapter("Fun with Magnets", listOf(NcertTopic("Magnetic Materials"), NcertTopic("Poles of Magnet"), NcertTopic("Earth's Magnetism"))),
            NcertChapter("Water", listOf(NcertTopic("Water Cycle"), NcertTopic("Conservation"), NcertTopic("Water Pollution"))),
            NcertChapter("Air Around Us", listOf(NcertTopic("Composition of Air"), NcertTopic("Importance of Air"))),
            NcertChapter("Garbage In, Garbage Out", listOf(NcertTopic("Waste Disposal"), NcertTopic("Composting"), NcertTopic("Recycling"))),
        )),

        NcertSyllabus("Class 6", "Social Science", listOf(
            NcertChapter("What, Where, How and When? (History)", listOf(NcertTopic("Sources of History"), NcertTopic("Dates and Periods"))),
            NcertChapter("On the Trail of the Earliest People (History)", listOf(NcertTopic("Hunter-Gatherers"), NcertTopic("Stone Tools"))),
            NcertChapter("From Gathering to Growing Food (History)", listOf(NcertTopic("Neolithic Period"), NcertTopic("First Farmers"))),
            NcertChapter("In the Earliest Cities (History)", listOf(NcertTopic("Harappan Civilization"), NcertTopic("Urban Planning"))),
            NcertChapter("The Earth in the Solar System (Geography)", listOf(NcertTopic("Planets"), NcertTopic("Stars"), NcertTopic("Constellations"))),
            NcertChapter("Globe: Latitudes and Longitudes (Geography)", listOf(NcertTopic("Latitudes"), NcertTopic("Longitudes"), NcertTopic("Time Zones"))),
            NcertChapter("Motions of the Earth (Geography)", listOf(NcertTopic("Rotation"), NcertTopic("Revolution"))),
            NcertChapter("Maps (Geography)", listOf(NcertTopic("Types of Maps"), NcertTopic("Map Symbols"))),
            NcertChapter("Understanding Diversity (Civics)", listOf(NcertTopic("Diversity in India"), NcertTopic("Unity in Diversity"))),
            NcertChapter("Diversity and Discrimination (Civics)", listOf(NcertTopic("Prejudice"), NcertTopic("Inequality"))),
            NcertChapter("What is Government? (Civics)", listOf(NcertTopic("Types of Government"), NcertTopic("Democracy"))),
            NcertChapter("Key Elements of a Democratic Government (Civics)", listOf(NcertTopic("Participation"), NcertTopic("Equality and Justice"))),
        )),

        NcertSyllabus("Class 6", "English", listOf(
            NcertChapter("Who Did Patrick's Homework?", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Grammar - Nouns"))),
            NcertChapter("How the Dog Found Himself a New Master", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Vocabulary"))),
            NcertChapter("Taro's Reward", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Moral Values"))),
            NcertChapter("An Indian-American Woman in Space: Kalpana Chawla", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Inspirational Figures"))),
            NcertChapter("A Different Kind of School", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Empathy"))),
            NcertChapter("Who I Am", listOf(NcertTopic("Self-Awareness"), NcertTopic("Individuality"))),
            NcertChapter("Fair Play", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Justice and Fairness"))),
            NcertChapter("Vocation", listOf(NcertTopic("Poem Analysis"), NcertTopic("Careers"))),
            NcertChapter("Desert Animals", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Adaptation"))),
            NcertChapter("The Banyan Tree", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Nature"))),
        )),

        NcertSyllabus("Class 6", "Hindi", listOf(
            NcertChapter("वह चिड़िया जो (कविता)", listOf(NcertTopic("कविता वाचन"), NcertTopic("भावार्थ"))),
            NcertChapter("बचपन (संस्मरण)", listOf(NcertTopic("संस्मरण विधा"), NcertTopic("बचपन की स्मृतियाँ"))),
            NcertChapter("नादान दोस्त (कहानी)", listOf(NcertTopic("कहानी वाचन"), NcertTopic("चरित्र चित्रण"))),
            NcertChapter("चाँद तारे मेरे ठेले पर (कविता)", listOf(NcertTopic("कविता वाचन"), NcertTopic("कल्पना"))),
            NcertChapter("झूठा बाबा (कहानी)", listOf(NcertTopic("कहानी वाचन"), NcertTopic("नैतिक मूल्य"))),
            NcertChapter("प्रेमचंद के फटे जूते (कहानी)", listOf(NcertTopic("कहानी वाचन"), NcertTopic("हास्य विधा"))),
            NcertChapter("साथी हाथ बढ़ाना (कविता)", listOf(NcertTopic("कविता वाचन"), NcertTopic("सहयोग"))),
            NcertChapter("ऐसे ऐसे (एकांकी)", listOf(NcertTopic("एकांकी विधा"), NcertTopic("हास्य"))),
            NcertChapter("टिकट एल्बम (कहानी)", listOf(NcertTopic("कहानी वाचन"), NcertTopic("संवाद"))),
            NcertChapter("झांसी की रानी (कविता)", listOf(NcertTopic("कविता वाचन"), NcertTopic("वीर रस"))),
        )),

        // ════ CLASS 7 ════
        NcertSyllabus("Class 7", "Mathematics", listOf(
            NcertChapter("Integers", listOf(NcertTopic("Properties of Integers"), NcertTopic("Multiplication of Integers"), NcertTopic("Division of Integers"))),
            NcertChapter("Fractions and Decimals", listOf(NcertTopic("Multiplication of Fractions"), NcertTopic("Division of Fractions"), NcertTopic("Decimals Operations"))),
            NcertChapter("Data Handling", listOf(NcertTopic("Collecting Data"), NcertTopic("Mean, Median, Mode"), NcertTopic("Bar Graphs and Probability"))),
            NcertChapter("Simple Equations", listOf(NcertTopic("Setting up Equations"), NcertTopic("Solving Equations"), NcertTopic("Applications"))),
            NcertChapter("Lines and Angles", listOf(NcertTopic("Related Angles"), NcertTopic("Pairs of Lines"))),
            NcertChapter("The Triangle and Its Properties", listOf(NcertTopic("Medians and Altitudes"), NcertTopic("Angle Sum Property"), NcertTopic("Pythagoras Theorem"))),
            NcertChapter("Congruence of Triangles", listOf(NcertTopic("Congruence Conditions"), NcertTopic("SAS, ASA, SSS, RHS"))),
            NcertChapter("Comparing Quantities", listOf(NcertTopic("Equivalent Ratios"), NcertTopic("Percentage"), NcertTopic("Profit and Loss"))),
            NcertChapter("Rational Numbers", listOf(NcertTopic("Positive and Negative Rational Numbers"), NcertTopic("Operations on Rational Numbers"))),
            NcertChapter("Practical Geometry", listOf(NcertTopic("Construction of Triangles"), NcertTopic("Construction of Parallel Lines"))),
            NcertChapter("Perimeter and Area", listOf(NcertTopic("Area of Rectangles and Squares"), NcertTopic("Area of Parallelogram and Triangle"), NcertTopic("Circumference of Circle"))),
            NcertChapter("Algebraic Expressions", listOf(NcertTopic("Terms of Expression"), NcertTopic("Like and Unlike Terms"), NcertTopic("Addition and Subtraction"))),
            NcertChapter("Exponents and Powers", listOf(NcertTopic("Laws of Exponents"), NcertTopic("Standard Form"))),
            NcertChapter("Symmetry", listOf(NcertTopic("Line Symmetry"), NcertTopic("Rotational Symmetry"))),
            NcertChapter("Visualising Solid Shapes", listOf(NcertTopic("Faces, Edges, Vertices"), NcertTopic("Nets of Solids"))),
        )),

        NcertSyllabus("Class 7", "Science", listOf(
            NcertChapter("Nutrition in Plants", listOf(NcertTopic("Photosynthesis"), NcertTopic("Modes of Nutrition"), NcertTopic("Saprophytic and Parasitic"))),
            NcertChapter("Nutrition in Animals", listOf(NcertTopic("Digestion in Humans"), NcertTopic("Digestion in Grass-eating Animals"), NcertTopic("Amoeba Digestion"))),
            NcertChapter("Fibre to Fabric", listOf(NcertTopic("Wool"), NcertTopic("Silk"))),
            NcertChapter("Heat", listOf(NcertTopic("Hot and Cold"), NcertTopic("Temperature Measurement"), NcertTopic("Transfer of Heat"))),
            NcertChapter("Acids, Bases and Salts", listOf(NcertTopic("Acids and Bases"), NcertTopic("Neutralisation"), NcertTopic("Indicators"))),
            NcertChapter("Physical and Chemical Changes", listOf(NcertTopic("Physical Changes"), NcertTopic("Chemical Changes"), NcertTopic("Rusting of Iron"))),
            NcertChapter("Weather, Climate and Adaptations", listOf(NcertTopic("Weather"), NcertTopic("Climate"), NcertTopic("Adaptations"))),
            NcertChapter("Winds, Storms and Cyclones", listOf(NcertTopic("Air Pressure"), NcertTopic("Wind Currents"), NcertTopic("Cyclones"))),
            NcertChapter("Soil", listOf(NcertTopic("Soil Profile"), NcertTopic("Types of Soil"), NcertTopic("Soil Conservation"))),
            NcertChapter("Respiration in Organisms", listOf(NcertTopic("Aerobic and Anaerobic Respiration"), NcertTopic("Breathing"))),
            NcertChapter("Transportation in Animals and Plants", listOf(NcertTopic("Circulatory System"), NcertTopic("Transport in Plants"))),
            NcertChapter("Reproduction in Plants", listOf(NcertTopic("Vegetative Propagation"), NcertTopic("Sexual Reproduction"), NcertTopic("Seed Dispersal"))),
            NcertChapter("Motion and Time", listOf(NcertTopic("Measurement of Time"), NcertTopic("Speed"), NcertTopic("Distance-Time Graph"))),
            NcertChapter("Electric Current and Its Effects", listOf(NcertTopic("Electric Circuit"), NcertTopic("Heating Effect"), NcertTopic("Magnetic Effect"))),
            NcertChapter("Light", listOf(NcertTopic("Reflection of Light"), NcertTopic("Plane Mirrors"), NcertTopic("Spherical Mirrors and Lenses"))),
            NcertChapter("Water: A Precious Resource", listOf(NcertTopic("Water Cycle"), NcertTopic("Groundwater"), NcertTopic("Water Management"))),
            NcertChapter("Forests: Our Lifeline", listOf(NcertTopic("Forest Ecosystem"), NcertTopic("Conservation"))),
            NcertChapter("Wastewater Story", listOf(NcertTopic("Wastewater Treatment"), NcertTopic("Sanitation"))),
        )),

        NcertSyllabus("Class 7", "Social Science", listOf(
            NcertChapter("Tracing Changes Through a Thousand Years (History)", listOf(NcertTopic("New and Old Terminologies"), NcertTopic("Historical Sources"))),
            NcertChapter("New Kings and Kingdoms (History)", listOf(NcertTopic("Emergence of Dynasties"), NcertTopic("Administration"))),
            NcertChapter("The Delhi Sultans (History)", listOf(NcertTopic("Delhi Sultanate"), NcertTopic("Expansion of Empire"))),
            NcertChapter("The Mughal Empire (History)", listOf(NcertTopic("Mughal Rulers"), NcertTopic("Mansabdari System"))),
            NcertChapter("Environment (Geography)", listOf(NcertTopic("Natural and Human Environment"), NcertTopic("Ecosystem"))),
            NcertChapter("Inside Our Earth (Geography)", listOf(NcertTopic("Layers of Earth"), NcertTopic("Rocks and Minerals"))),
            NcertChapter("Our Changing Earth (Geography)", listOf(NcertTopic("Earth Movements"), NcertTopic("Earthquakes and Volcanoes"))),
            NcertChapter("Human Environment: Settlement, Transport and Communication (Geography)", listOf(NcertTopic("Settlements"), NcertTopic("Transport and Communication"))),
            NcertChapter("On Equality (Civics)", listOf(NcertTopic("Equality in Indian Democracy"), NcertTopic("Universal Adult Franchise"))),
            NcertChapter("Role of the Government in Health (Civics)", listOf(NcertTopic("Healthcare Services"), NcertTopic("Public vs Private Health"))),
            NcertChapter("How the State Government Works (Civics)", listOf(NcertTopic("State Legislature"), NcertTopic("State Executive"))),
            NcertChapter("Understanding Advertising (Civics)", listOf(NcertTopic("Types of Advertising"), NcertTopic("Impact of Advertising"))),
        )),

        NcertSyllabus("Class 7", "English", listOf(
            NcertChapter("Three Questions", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Wisdom and Knowledge"))),
            NcertChapter("A Gift of Chappals", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Kindness and Innocence"))),
            NcertChapter("Gopal and the Hilsa Fish", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Humour"))),
            NcertChapter("The Ashes That Made Trees Bloom", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Justice and Reward"))),
            NcertChapter("Quality", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Dedication and Craftsmanship"))),
            NcertChapter("Expert Detectives", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Mystery and Investigation"))),
            NcertChapter("The Invention of Vita-Wonk", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Imagination and Humour"))),
            NcertChapter("Fire: Friend and Foe", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Science of Fire"))),
            NcertChapter("A Bicycle in Good Repair", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Humour"))),
            NcertChapter("The Story of Cricket", listOf(NcertTopic("Reading Comprehension"), NcertTopic("History of Sports"))),
        )),

        // ════ CLASS 8 ════
        NcertSyllabus("Class 8", "Mathematics", listOf(
            NcertChapter("Rational Numbers", listOf(NcertTopic("Properties of Rational Numbers"), NcertTopic("Representation on Number Line"))),
            NcertChapter("Linear Equations in One Variable", listOf(NcertTopic("Solving Linear Equations"), NcertTopic("Applications"))),
            NcertChapter("Understanding Quadrilaterals", listOf(NcertTopic("Polygons"), NcertTopic("Types of Quadrilaterals"), NcertTopic("Properties"))),
            NcertChapter("Data Handling", listOf(NcertTopic("Grouped Data"), NcertTopic("Pie Chart"), NcertTopic("Probability"))),
            NcertChapter("Squares and Square Roots", listOf(NcertTopic("Properties of Squares"), NcertTopic("Finding Square Roots"))),
            NcertChapter("Cubes and Cube Roots", listOf(NcertTopic("Properties of Cubes"), NcertTopic("Finding Cube Roots"))),
            NcertChapter("Comparing Quantities", listOf(NcertTopic("Percentage"), NcertTopic("Compound Interest"), NcertTopic("Discount and Tax"))),
            NcertChapter("Algebraic Expressions and Identities", listOf(NcertTopic("Multiplication of Expressions"), NcertTopic("Standard Identities"))),
            NcertChapter("Mensuration", listOf(NcertTopic("Area of Trapezium and Polygon"), NcertTopic("Volume of Solids"))),
            NcertChapter("Exponents and Powers", listOf(NcertTopic("Laws of Exponents"), NcertTopic("Negative Exponents"))),
            NcertChapter("Direct and Inverse Proportions", listOf(NcertTopic("Direct Proportion"), NcertTopic("Inverse Proportion"))),
            NcertChapter("Factorisation", listOf(NcertTopic("Factorising Algebraic Expressions"), NcertTopic("Division of Expressions"))),
            NcertChapter("Introduction to Graphs", listOf(NcertTopic("Bar Graphs"), NcertTopic("Line Graphs"), NcertTopic("Linear Graphs"))),
            NcertChapter("Playing with Numbers", listOf(NcertTopic("Divisibility Rules"), NcertTopic("Number Games"))),
        )),

        NcertSyllabus("Class 8", "Science", listOf(
            NcertChapter("Crop Production and Management", listOf(NcertTopic("Agricultural Practices"), NcertTopic("Kharif and Rabi Crops"), NcertTopic("Fertilisers"))),
            NcertChapter("Microorganisms: Friend and Foe", listOf(NcertTopic("Bacteria, Fungi, Protozoa"), NcertTopic("Useful Microorganisms"), NcertTopic("Harmful Microorganisms"))),
            NcertChapter("Synthetic Fibres and Plastics", listOf(NcertTopic("Nylon, Rayon, Polyester"), NcertTopic("Plastics and Environment"))),
            NcertChapter("Materials: Metals and Non-Metals", listOf(NcertTopic("Physical Properties"), NcertTopic("Chemical Properties"), NcertTopic("Uses"))),
            NcertChapter("Coal and Petroleum", listOf(NcertTopic("Formation of Coal"), NcertTopic("Petroleum Refining"), NcertTopic("Conservation"))),
            NcertChapter("Combustion and Flame", listOf(NcertTopic("Types of Combustion"), NcertTopic("Flame Structure"), NcertTopic("Fuel Efficiency"))),
            NcertChapter("Conservation of Plants and Animals", listOf(NcertTopic("Deforestation"), NcertTopic("Wildlife Conservation"), NcertTopic("Biosphere Reserves"))),
            NcertChapter("Cell: Structure and Functions", listOf(NcertTopic("Cell Organelles"), NcertTopic("Plant vs Animal Cell"), NcertTopic("Cell Division"))),
            NcertChapter("Reproduction in Animals", listOf(NcertTopic("Sexual Reproduction"), NcertTopic("Asexual Reproduction"), NcertTopic("Metamorphosis"))),
            NcertChapter("Reaching the Age of Adolescence", listOf(NcertTopic("Puberty"), NcertTopic("Hormones"), NcertTopic("Reproductive Health"))),
            NcertChapter("Force and Pressure", listOf(NcertTopic("Types of Forces"), NcertTopic("Pressure in Fluids"))),
            NcertChapter("Friction", listOf(NcertTopic("Types of Friction"), NcertTopic("Increasing and Reducing Friction"))),
            NcertChapter("Sound", listOf(NcertTopic("Production and Propagation"), NcertTopic("Human Ear"), NcertTopic("Noise Pollution"))),
            NcertChapter("Chemical Effects of Electric Current", listOf(NcertTopic("Electrolysis"), NcertTopic("Electroplating"))),
            NcertChapter("Some Natural Phenomena", listOf(NcertTopic("Lightning"), NcertTopic("Earthquakes"))),
            NcertChapter("Light", listOf(NcertTopic("Reflection"), NcertTopic("Human Eye"), NcertTopic("Dispersion of Light"))),
            NcertChapter("Stars and the Solar System", listOf(NcertTopic("Celestial Objects"), NcertTopic("Phases of Moon"), NcertTopic("Constellations"))),
            NcertChapter("Pollution of Air and Water", listOf(NcertTopic("Air Pollution"), NcertTopic("Water Pollution"), NcertTopic("Conservation"))),
        )),

        NcertSyllabus("Class 8", "Social Science", listOf(
            NcertChapter("How, When and Where (History)", listOf(NcertTopic("Historical Dates"), NcertTopic("Sources of Modern History"))),
            NcertChapter("From Trade to Territory (History)", listOf(NcertTopic("East India Company"), NcertTopic("Battle of Plassey"), NcertTopic("Battle of Buxar"))),
            NcertChapter("Ruling the Countryside (History)", listOf(NcertTopic("Permanent Settlement"), NcertTopic("Ryotwari System"))),
            NcertChapter("Tribals, Dikus and the Vision of a Golden Age (History)", listOf(NcertTopic("Tribal Societies"), NcertTopic("Birsa Munda"))),
            NcertChapter("When People Rebel 1857 (History)", listOf(NcertTopic("Revolt of 1857"), NcertTopic("Causes and Consequences"))),
            NcertChapter("Colonialism and the City (History)", listOf(NcertTopic("Urbanisation under British"), NcertTopic("Decline of Old Cities"))),
            NcertChapter("Resources (Geography)", listOf(NcertTopic("Types of Resources"), NcertTopic("Conservation"))),
            NcertChapter("Land, Soil, Water, Natural Vegetation and Wildlife (Geography)", listOf(NcertTopic("Land Use"), NcertTopic("Soil Conservation"), NcertTopic("Water Conservation"))),
            NcertChapter("Mineral and Power Resources (Geography)", listOf(NcertTopic("Types of Minerals"), NcertTopic("Conventional and Non-conventional Energy"))),
            NcertChapter("Agriculture (Geography)", listOf(NcertTopic("Types of Farming"), NcertTopic("Major Crops"))),
            NcertChapter("Industries (Geography)", listOf(NcertTopic("Classification of Industries"), NcertTopic("Industrial Location"))),
            NcertChapter("Human Resources (Geography)", listOf(NcertTopic("Population Distribution"), NcertTopic("Human Resource Development"))),
            NcertChapter("The Indian Constitution (Civics)", listOf(NcertTopic("Need for Constitution"), NcertTopic("Key Features"))),
            NcertChapter("Understanding Secularism (Civics)", listOf(NcertTopic("Meaning of Secularism"), NcertTopic("Secularism in India"))),
            NcertChapter("Why Do We Need a Parliament? (Civics)", listOf(NcertTopic("Parliament"), NcertTopic("People's Representation"))),
            NcertChapter("Understanding Laws (Civics)", listOf(NcertTopic("Rule of Law"), NcertTopic("Types of Laws"))),
            NcertChapter("Understanding Our Criminal Justice System (Civics)", listOf(NcertTopic("Police and FIR"), NcertTopic("Fair Trial"))),
            NcertChapter("Understanding Marginalisation (Civics)", listOf(NcertTopic("Marginalised Communities"), NcertTopic("Adivasis and Minorities"))),
        )),

        NcertSyllabus("Class 8", "English", listOf(
            NcertChapter("The Best Christmas Present in the World", listOf(NcertTopic("Reading Comprehension"), NcertTopic("War and Peace"))),
            NcertChapter("The Tsunami", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Natural Disasters"))),
            NcertChapter("Glimpses of the Past", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Indian History"))),
            NcertChapter("Bepin Choudhury's Lapse of Memory", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Humour"))),
            NcertChapter("The Summit Within", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Adventure and Perseverance"))),
            NcertChapter("This is Jody's Fawn", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Compassion for Animals"))),
            NcertChapter("A Visit to Cambridge", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Disability and Achievement"))),
            NcertChapter("A Short Monsoon Diary", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Nature Writing"))),
            NcertChapter("The Great Stone Face I", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Legend and Prophecy"))),
            NcertChapter("The Great Stone Face II", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Fulfillment of Prophecy"))),
        )),

        // ════ CLASS 9 ════
        NcertSyllabus("Class 9", "Mathematics", listOf(
            NcertChapter("Number Systems", listOf(NcertTopic("Rational and Irrational Numbers"), NcertTopic("Real Numbers on Number Line"), NcertTopic("Operations on Real Numbers"))),
            NcertChapter("Polynomials", listOf(NcertTopic("Types of Polynomials"), NcertTopic("Zeroes of Polynomials"), NcertTopic("Factor Theorem"))),
            NcertChapter("Coordinate Geometry", listOf(NcertTopic("Cartesian System"), NcertTopic("Plotting Points"))),
            NcertChapter("Linear Equations in Two Variables", listOf(NcertTopic("Graph of Linear Equations"), NcertTopic("Solutions"))),
            NcertChapter("Introduction to Euclid's Geometry", listOf(NcertTopic("Euclid's Definitions"), NcertTopic("Axioms and Postulates"))),
            NcertChapter("Lines and Angles", listOf(NcertTopic("Angle Properties"), NcertTopic("Parallel Lines"))),
            NcertChapter("Triangles", listOf(NcertTopic("Congruence Criteria"), NcertTopic("Inequalities in Triangles"))),
            NcertChapter("Quadrilaterals", listOf(NcertTopic("Properties of Parallelograms"), NcertTopic("Mid-point Theorem"))),
            NcertChapter("Circles", listOf(NcertTopic("Chord and Arc Properties"), NcertTopic("Angle Subtended by Chords"))),
            NcertChapter("Heron's Formula", listOf(NcertTopic("Area of Triangle"), NcertTopic("Application in Quadrilaterals"))),
            NcertChapter("Surface Areas and Volumes", listOf(NcertTopic("Cuboid and Cube"), NcertTopic("Cylinder and Cone"), NcertTopic("Sphere"))),
            NcertChapter("Statistics", listOf(NcertTopic("Data Collection"), NcertTopic("Mean, Median, Mode"), NcertTopic("Histogram"))),
            NcertChapter("Probability", listOf(NcertTopic("Experimental Probability"), NcertTopic("Sample Space"))),
        )),

        NcertSyllabus("Class 9", "Science", listOf(
            NcertChapter("Matter in Our Surroundings", listOf(NcertTopic("States of Matter"), NcertTopic("Interconversion of States"))),
            NcertChapter("Is Matter Around Us Pure?", listOf(NcertTopic("Mixtures and Solutions"), NcertTopic("Separation Techniques"), NcertTopic("Elements and Compounds"))),
            NcertChapter("Atoms and Molecules", listOf(NcertTopic("Laws of Chemical Combination"), NcertTopic("Mole Concept"))),
            NcertChapter("Structure of the Atom", listOf(NcertTopic("Subatomic Particles"), NcertTopic("Bohr's Model"), NcertTopic("Electronic Configuration"))),
            NcertChapter("The Fundamental Unit of Life", listOf(NcertTopic("Cell Theory"), NcertTopic("Cell Organelles"), NcertTopic("Osmosis and Diffusion"))),
            NcertChapter("Tissues", listOf(NcertTopic("Plant Tissues"), NcertTopic("Animal Tissues"))),
            NcertChapter("Diversity in Living Organisms", listOf(NcertTopic("Classification"), NcertTopic("Five Kingdom Classification"))),
            NcertChapter("Motion", listOf(NcertTopic("Distance and Displacement"), NcertTopic("Velocity and Acceleration"), NcertTopic("Equations of Motion"))),
            NcertChapter("Force and Laws of Motion", listOf(NcertTopic("Newton's Laws"), NcertTopic("Momentum and Inertia"))),
            NcertChapter("Gravitation", listOf(NcertTopic("Universal Law of Gravitation"), NcertTopic("Free Fall"), NcertTopic("Buoyancy"))),
            NcertChapter("Work and Energy", listOf(NcertTopic("Work Done"), NcertTopic("Kinetic and Potential Energy"), NcertTopic("Power"))),
            NcertChapter("Sound", listOf(NcertTopic("Production and Propagation"), NcertTopic("Reflection of Sound"), NcertTopic("Range of Hearing"))),
            NcertChapter("Why Do We Fall Ill?", listOf(NcertTopic("Types of Diseases"), NcertTopic("Causes and Prevention"))),
            NcertChapter("Natural Resources", listOf(NcertTopic("Air and Water"), NcertTopic("Biogeochemical Cycles"))),
            NcertChapter("Improvement in Food Resources", listOf(NcertTopic("Crop Improvement"), NcertTopic("Animal Husbandry"))),
        )),

        NcertSyllabus("Class 9", "Social Science", listOf(
            NcertChapter("The French Revolution (History)", listOf(NcertTopic("Causes of Revolution"), NcertTopic("Outbreak and Consequences"), NcertTopic("Abolition of Monarchy"))),
            NcertChapter("Socialism in Europe and the Russian Revolution (History)", listOf(NcertTopic("Rise of Socialism"), NcertTopic("October Revolution"))),
            NcertChapter("Nazism and the Rise of Hitler (History)", listOf(NcertTopic("Rise of Nazism"), NcertTopic("Nazi Ideology"), NcertTopic("Consequences"))),
            NcertChapter("Forest Society and Colonialism (History)", listOf(NcertTopic("Deforestation under Colonial Rule"), NcertTopic("Forest Rebellions"))),
            NcertChapter("Pastoralists in the Modern World (History)", listOf(NcertTopic("Nomadic Communities"), NcertTopic("Colonial Impact"))),
            NcertChapter("India: Size and Location (Geography)", listOf(NcertTopic("Location of India"), NcertTopic("Standard Meridian"))),
            NcertChapter("Physical Features of India (Geography)", listOf(NcertTopic("Himalayan Mountains"), NcertTopic("Northern Plains"), NcertTopic("Peninsular Plateau"))),
            NcertChapter("Drainage (Geography)", listOf(NcertTopic("Himalayan Rivers"), NcertTopic("Peninsular Rivers"), NcertTopic("Lakes"))),
            NcertChapter("Climate (Geography)", listOf(NcertTopic("Climatic Controls"), NcertTopic("Monsoon"), NcertTopic("Distribution of Rainfall"))),
            NcertChapter("Natural Vegetation and Wildlife (Geography)", listOf(NcertTopic("Types of Vegetation"), NcertTopic("Wildlife Conservation"))),
            NcertChapter("Population (Geography)", listOf(NcertTopic("Population Size and Distribution"), NcertTopic("Population Growth"), NcertTopic("Population Composition"))),
            NcertChapter("What is Democracy? Why Democracy? (Civics)", listOf(NcertTopic("Features of Democracy"), NcertTopic("Arguments For and Against"))),
            NcertChapter("Constitutional Design (Civics)", listOf(NcertTopic("Making of Indian Constitution"), NcertTopic("Guiding Values"))),
            NcertChapter("Electoral Politics (Civics)", listOf(NcertTopic("Elections in India"), NcertTopic("Voting System"))),
            NcertChapter("Working of Institutions (Civics)", listOf(NcertTopic("Parliament"), NcertTopic("Executive"), NcertTopic("Judiciary"))),
            NcertChapter("Democratic Rights (Civics)", listOf(NcertTopic("Fundamental Rights"), NcertTopic("Human Rights"))),
            NcertChapter("The Story of Village Palampur (Economics)", listOf(NcertTopic("Factors of Production"), NcertTopic("Farming in Palampur"))),
            NcertChapter("People as Resource (Economics)", listOf(NcertTopic("Human Capital"), NcertTopic("Unemployment"))),
            NcertChapter("Poverty as a Challenge (Economics)", listOf(NcertTopic("Poverty Line"), NcertTopic("Causes of Poverty"))),
            NcertChapter("Food Security in India (Economics)", listOf(NcertTopic("Food Security"), NcertTopic("Public Distribution System"))),
        )),

        NcertSyllabus("Class 9", "English", listOf(
            NcertChapter("The Fun They Had", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Future of Education"))),
            NcertChapter("The Sound of Music", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Evelyn Glennie"), NcertTopic("Bismillah Khan"))),
            NcertChapter("Reach for the Top", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Santosh Yadav"), NcertTopic("Maria Sharapova"))),
            NcertChapter("Wind (Poem)", listOf(NcertTopic("Poem Analysis"), NcertTopic("Symbolism"))),
            NcertChapter("The Little Girl", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Father-Daughter Relationship"))),
            NcertChapter("A Truly Beautiful Mind", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Albert Einstein"))),
            NcertChapter("My Childhood", listOf(NcertTopic("Reading Comprehension"), NcertTopic("APJ Abdul Kalam"))),
            NcertChapter("No Men Are Foreign (Poem)", listOf(NcertTopic("Poem Analysis"), NcertTopic("Universal Brotherhood"))),
            NcertChapter("The Beggar", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Compassion and Transformation"))),
        )),
    )
}
