package com.littlebridge.enrollplus.feature.ai

import com.littlebridge.enrollplus.feature.ai.NcertReferenceService.NcertChapter
import com.littlebridge.enrollplus.feature.ai.NcertReferenceService.NcertSyllabus
import com.littlebridge.enrollplus.feature.ai.NcertReferenceService.NcertTopic

/**
 * NCERT syllabus reference data — Part 2 (Class 10-12).
 * Source: NCERT official syllabus (ncert.nic.in)
 */
object NcertReferenceData2 {
    val DATA: List<NcertSyllabus> = listOf(

        // ════ CLASS 10 ════
        NcertSyllabus("Class 10", "Mathematics", listOf(
            NcertChapter("Real Numbers", listOf(NcertTopic("Euclid's Division Lemma"), NcertTopic("Fundamental Theorem of Arithmetic"), NcertTopic("HCF and LCM"))),
            NcertChapter("Polynomials", listOf(NcertTopic("Geometrical Meaning of Zeroes"), NcertTopic("Relationship Between Zeroes and Coefficients"))),
            NcertChapter("Pair of Linear Equations in Two Variables", listOf(NcertTopic("Graphical Method"), NcertTopic("Substitution and Elimination"), NcertTopic("Cross-Multiplication"))),
            NcertChapter("Quadratic Equations", listOf(NcertTopic("Solution by Factorisation"), NcertTopic("Quadratic Formula"), NcertTopic("Nature of Roots"))),
            NcertChapter("Arithmetic Progressions", listOf(NcertTopic("nth Term"), NcertTopic("Sum of n Terms"))),
            NcertChapter("Triangles", listOf(NcertTopic("Similarity of Triangles"), NcertTopic("Pythagoras Theorem"))),
            NcertChapter("Coordinate Geometry", listOf(NcertTopic("Distance Formula"), NcertTopic("Section Formula"), NcertTopic("Area of Triangle"))),
            NcertChapter("Introduction to Trigonometry", listOf(NcertTopic("Trigonometric Ratios"), NcertTopic("Trigonometric Identities"))),
            NcertChapter("Some Applications of Trigonometry", listOf(NcertTopic("Heights and Distances"))),
            NcertChapter("Circles", listOf(NcertTopic("Tangent to a Circle"), NcertTopic("Number of Tangents from a Point"))),
            NcertChapter("Areas Related to Circles", listOf(NcertTopic("Area of Sector and Segment"))),
            NcertChapter("Surface Areas and Volumes", listOf(NcertTopic("Combination of Solids"), NcertTopic("Conversion of Solids"))),
            NcertChapter("Statistics", listOf(NcertTopic("Mean of Grouped Data"), NcertTopic("Median and Mode"))),
            NcertChapter("Probability", listOf(NcertTopic("Classical Definition"), NcertTopic("Simple Problems"))),
        )),

        NcertSyllabus("Class 10", "Science", listOf(
            NcertChapter("Chemical Reactions and Equations", listOf(NcertTopic("Types of Reactions"), NcertTopic("Oxidation and Reduction"), NcertTopic("Effects of Oxidation"))),
            NcertChapter("Acids, Bases and Salts", listOf(NcertTopic("Chemical Properties"), NcertTopic("pH Scale"), NcertTopic("Salt Formation"))),
            NcertChapter("Metals and Non-Metals", listOf(NcertTopic("Physical Properties"), NcertTopic("Chemical Properties"), NcertTopic("Extraction of Metals"))),
            NcertChapter("Carbon and Its Compounds", listOf(NcertTopic("Bonding in Carbon"), NcertTopic("Hydrocarbons"), NcertTopic("Functional Groups"))),
            NcertChapter("Periodic Classification of Elements", listOf(NcertTopic("Mendeleev's Periodic Table"), NcertTopic("Modern Periodic Table"))),
            NcertChapter("Life Processes", listOf(NcertTopic("Nutrition"), NcertTopic("Respiration"), NcertTopic("Transportation"), NcertTopic("Excretion"))),
            NcertChapter("Control and Coordination", listOf(NcertTopic("Nervous System"), NcertTopic("Hormones in Animals"), NcertTopic("Plant Hormones"))),
            NcertChapter("How Do Organisms Reproduce?", listOf(NcertTopic("Sexual Reproduction in Plants"), NcertTopic("Reproduction in Humans"), NcertTopic("Reproductive Health"))),
            NcertChapter("Heredity and Evolution", listOf(NcertTopic("Mendel's Experiments"), NcertTopic("Sex Determination"), NcertTopic("Evolution"))),
            NcertChapter("Light: Reflection and Refraction", listOf(NcertTopic("Reflection by Spherical Mirrors"), NcertTopic("Refraction and Lens"))),
            NcertChapter("Human Eye and Colourful World", listOf(NcertTopic("Human Eye"), NcertTopic("Defects of Vision"), NcertTopic("Dispersion and Scattering"))),
            NcertChapter("Electricity", listOf(NcertTopic("Electric Current and Circuit"), NcertTopic("Ohm's Law"), NcertTopic("Electric Power"))),
            NcertChapter("Magnetic Effects of Electric Current", listOf(NcertTopic("Magnetic Field"), NcertTopic("Electromagnetic Induction"), NcertTopic("Domestic Circuits"))),
            NcertChapter("Sources of Energy", listOf(NcertTopic("Conventional Sources"), NcertTopic("Non-conventional Sources"))),
            NcertChapter("Our Environment", listOf(NcertTopic("Ecosystem"), NcertTopic("Food Chains"), NcertTopic("Waste Management"))),
            NcertChapter("Sustainable Management of Natural Resources", listOf(NcertTopic("Water Conservation"), NcertTopic("Forest and Wildlife Conservation"))),
        )),

        NcertSyllabus("Class 10", "Social Science", listOf(
            NcertChapter("The Rise of Nationalism in Europe (History)", listOf(NcertTopic("French Revolution and Nationalism"), NcertTopic("Unification of Germany and Italy"))),
            NcertChapter("Nationalism in India (History)", listOf(NcertTopic("Non-Cooperation Movement"), NcertTopic("Civil Disobedience Movement"))),
            NcertChapter("The Making of a Global World (History)", listOf(NcertTopic("Globalisation in 19th Century"), NcertTopic("Great Depression"))),
            NcertChapter("The Age of Industrialisation (History)", listOf(NcertTopic("Industrial Revolution"), NcertTopic("Industrialisation in India"))),
            NcertChapter("Print Culture and the Modern World (History)", listOf(NcertTopic("First Printed Books"), NcertTopic("Print in India"))),
            NcertChapter("Resources and Development (Geography)", listOf(NcertTopic("Types of Resources"), NcertTopic("Land Use"), NcertTopic("Soil Conservation"))),
            NcertChapter("Forest and Wildlife Resources (Geography)", listOf(NcertTopic("Biodiversity"), NcertTopic("Conservation"))),
            NcertChapter("Water Resources (Geography)", listOf(NcertTopic("Water Scarcity"), NcertTopic("Dams and Multipurpose Projects"))),
            NcertChapter("Agriculture (Geography)", listOf(NcertTopic("Types of Farming"), NcertTopic("Cropping Pattern"), NcertTopic("Agricultural Reforms"))),
            NcertChapter("Minerals and Energy Resources (Geography)", listOf(NcertTopic("Types of Minerals"), NcertTopic("Energy Resources"))),
            NcertChapter("Manufacturing Industries (Geography)", listOf(NcertTopic("Industrial Location"), NcertTopic("Types of Industries"))),
            NcertChapter("Lifelines of National Economy (Geography)", listOf(NcertTopic("Transport"), NcertTopic("Communication"), NcertTopic("Trade and Tourism"))),
            NcertChapter("Power Sharing (Civics)", listOf(NcertTopic("Forms of Power Sharing"), NcertTopic("Belgium and Sri Lanka"))),
            NcertChapter("Federalism (Civics)", listOf(NcertTopic("Federal System in India"), NcertTopic("Decentralisation"))),
            NcertChapter("Gender, Religion and Caste (Civics)", listOf(NcertTopic("Gender Inequality"), NcertTopic("Religion in Politics"), NcertTopic("Caste Politics"))),
            NcertChapter("Political Parties (Civics)", listOf(NcertTopic("Party System"), NcertTopic("National and Regional Parties"))),
            NcertChapter("Outcomes of Democracy (Civics)", listOf(NcertTopic("Accountability"), NcertTopic("Economic Growth and Equality"))),
            NcertChapter("Development (Economics)", listOf(NcertTopic("National Development"), NcertTopic("Human Development Index"))),
            NcertChapter("Sectors of the Indian Economy (Economics)", listOf(NcertTopic("Primary, Secondary, Tertiary Sectors"))),
            NcertChapter("Money and Credit (Economics)", listOf(NcertTopic("Functions of Money"), NcertTopic("Formal and Informal Credit"))),
            NcertChapter("Globalisation and the Indian Economy (Economics)", listOf(NcertTopic("Multinational Corporations"), NcertTopic("Impact of Globalisation"))),
            NcertChapter("Consumer Rights (Economics)", listOf(NcertTopic("Consumer Protection"), NcertTopic("Consumer Forums"))),
        )),

        NcertSyllabus("Class 10", "English", listOf(
            NcertChapter("A Letter to God", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Faith and Irony"))),
            NcertChapter("Nelson Mandela: Long Walk to Freedom", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Apartheid and Freedom"))),
            NcertChapter("Two Stories About Flying", listOf(NcertTopic("His First Flight"), NcertTopic("The Black Aeroplane"))),
            NcertChapter("From the Diary of Anne Frank", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Holocaust and Hope"))),
            NcertChapter("Glimpses of India", listOf(NcertTopic("A Baker from Goa"), NcertTopic("Coorg"), NcertTopic("Tea from Assam"))),
            NcertChapter("Mijbil the Otter", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Human-Animal Bond"))),
            NcertChapter("Madam Rides the Bus", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Childhood Curiosity"))),
            NcertChapter("The Sermon at Benares", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Teachings of Buddha"))),
            NcertChapter("The Proposal", listOf(NcertTopic("Reading Comprehension"), NcertTopic("Comedy and Human Nature"))),
            NcertChapter("Dust of Snow (Poem)", listOf(NcertTopic("Poem Analysis"), NcertTopic("Nature's Healing Power"))),
            NcertChapter("Fire and Ice (Poem)", listOf(NcertTopic("Poem Analysis"), NcertTopic("Destruction and Emotion"))),
            NcertChapter("A Tiger in the Zoo (Poem)", listOf(NcertTopic("Poem Analysis"), NcertTopic("Freedom and Captivity"))),
            NcertChapter("The Trees (Poem)", listOf(NcertTopic("Poem Analysis"), NcertTopic("Feminism and Freedom"))),
        )),

        // ════ CLASS 11 ════
        NcertSyllabus("Class 11", "Physics", listOf(
            NcertChapter("Physical World", listOf(NcertTopic("Scope of Physics"), NcertTopic("Technology and Society"))),
            NcertChapter("Units and Measurements", listOf(NcertTopic("SI Units"), NcertTopic("Significant Figures"), NcertTopic("Dimensional Analysis"))),
            NcertChapter("Motion in a Straight Line", listOf(NcertTopic("Displacement and Velocity"), NcertTopic("Uniformly Accelerated Motion"))),
            NcertChapter("Motion in a Plane", listOf(NcertTopic("Vectors"), NcertTopic("Projectile Motion"), NcertTopic("Relative Velocity"))),
            NcertChapter("Laws of Motion", listOf(NcertTopic("Newton's Laws"), NcertTopic("Friction"), NcertTopic("Circular Motion"))),
            NcertChapter("Work, Energy and Power", listOf(NcertTopic("Work-Energy Theorem"), NcertTopic("Conservation of Energy"), NcertTopic("Collisions"))),
            NcertChapter("System of Particles and Rotational Motion", listOf(NcertTopic("Centre of Mass"), NcertTopic("Torque and Angular Momentum"), NcertTopic("Moment of Inertia"))),
            NcertChapter("Gravitation", listOf(NcertTopic("Kepler's Laws"), NcertTopic("Universal Gravitation"), NcertTopic("Satellites"))),
            NcertChapter("Mechanical Properties of Solids", listOf(NcertTopic("Elasticity"), NcertTopic("Stress and Strain"), NcertTopic("Young's Modulus"))),
            NcertChapter("Mechanical Properties of Fluids", listOf(NcertTopic("Pressure"), NcertTopic("Bernoulli's Principle"), NcertTopic("Viscosity"))),
            NcertChapter("Thermal Properties of Matter", listOf(NcertTopic("Heat and Temperature"), NcertTopic("Thermal Expansion"), NcertTopic("Heat Transfer"))),
            NcertChapter("Thermodynamics", listOf(NcertTopic("First Law"), NcertTopic("Second Law"), NcertTopic("Carnot Engine"))),
            NcertChapter("Kinetic Theory of Gases", listOf(NcertTopic("Ideal Gas Law"), NcertTopic("Degrees of Freedom"))),
            NcertChapter("Oscillations", listOf(NcertTopic("Simple Harmonic Motion"), NcertTopic("Pendulum"))),
            NcertChapter("Waves", listOf(NcertTopic("Transverse and Longitudinal Waves"), NcertTopic("Doppler Effect"))),
        )),

        NcertSyllabus("Class 11", "Chemistry", listOf(
            NcertChapter("Some Basic Concepts of Chemistry", listOf(NcertTopic("Mole Concept"), NcertTopic("Stoichiometry"))),
            NcertChapter("Structure of Atom", listOf(NcertTopic("Bohr's Model"), NcertTopic("Quantum Numbers"), NcertTopic("Electronic Configuration"))),
            NcertChapter("Classification of Elements and Periodicity", listOf(NcertTopic("Modern Periodic Table"), NcertTopic("Periodic Trends"))),
            NcertChapter("Chemical Bonding and Molecular Structure", listOf(NcertTopic("Ionic and Covalent Bonds"), NcertTopic("VSEPR Theory"), NcertTopic("Hybridisation"))),
            NcertChapter("States of Matter", listOf(NcertTopic("Gas Laws"), NcertTopic("Ideal Gas Equation"), NcertTopic("Liquid State"))),
            NcertChapter("Thermodynamics", listOf(NcertTopic("Enthalpy"), NcertTopic("Entropy"), NcertTopic("Gibbs Energy"))),
            NcertChapter("Equilibrium", listOf(NcertTopic("Chemical Equilibrium"), NcertTopic("Le Chatelier's Principle"), NcertTopic("Ionic Equilibrium"))),
            NcertChapter("Redox Reactions", listOf(NcertTopic("Oxidation Number"), NcertTopic("Balancing Redox Reactions"))),
            NcertChapter("Hydrogen", listOf(NcertTopic("Properties of Hydrogen"), NcertTopic("Hydrogen Peroxide"))),
            NcertChapter("The s-Block Elements", listOf(NcertTopic("Group 1 Elements"), NcertTopic("Group 2 Elements"))),
            NcertChapter("The p-Block Elements", listOf(NcertTopic("Group 13 Elements"), NcertTopic("Group 14 Elements"))),
            NcertChapter("Organic Chemistry: Basic Principles", listOf(NcertTopic("Nomenclature"), NcertTopic("Isomerism"), NcertTopic("Reaction Mechanisms"))),
            NcertChapter("Hydrocarbons", listOf(NcertTopic("Alkanes"), NcertTopic("Alkenes"), NcertTopic("Alkynes"), NcertTopic("Aromatic Hydrocarbons"))),
            NcertChapter("Environmental Chemistry", listOf(NcertTopic("Air Pollution"), NcertTopic("Water Pollution"), NcertTopic("Green Chemistry"))),
        )),

        NcertSyllabus("Class 11", "Biology", listOf(
            NcertChapter("The Living World", listOf(NcertTopic("Diversity in Living World"), NcertTopic("Taxonomic Categories"))),
            NcertChapter("Biological Classification", listOf(NcertTopic("Five Kingdom Classification"), NcertTopic("Monera, Protista, Fungi"))),
            NcertChapter("Plant Kingdom", listOf(NcertTopic("Algae"), NcertTopic("Bryophytes"), NcertTopic("Pteridophytes"), NcertTopic("Gymnosperms"), NcertTopic("Angiosperms"))),
            NcertChapter("Animal Kingdom", listOf(NcertTopic("Invertebrates"), NcertTopic("Vertebrates"), NcertTopic("Classification Basis"))),
            NcertChapter("Morphology of Flowering Plants", listOf(NcertTopic("Root, Stem, Leaf"), NcertTopic("Flower"), NcertTopic("Fruit and Seed"))),
            NcertChapter("Anatomy of Flowering Plants", listOf(NcertTopic("Plant Tissues"), NcertTopic("Secondary Growth"))),
            NcertChapter("Structural Organisation in Animals", listOf(NcertTopic("Animal Tissues"), NcertTopic("Frog and Cockroach"))),
            NcertChapter("Cell: The Unit of Life", listOf(NcertTopic("Prokaryotic and Eukaryotic Cell"), NcertTopic("Cell Organelles"))),
            NcertChapter("Biomolecules", listOf(NcertTopic("Carbohydrates"), NcertTopic("Proteins"), NcertTopic("Lipids and Nucleic Acids"))),
            NcertChapter("Cell Cycle and Cell Division", listOf(NcertTopic("Mitosis"), NcertTopic("Meiosis"))),
            NcertChapter("Photosynthesis in Higher Plants", listOf(NcertTopic("Light Reactions"), NcertTopic("Calvin Cycle"))),
            NcertChapter("Respiration in Plants", listOf(NcertTopic("Glycolysis"), NcertTopic("Krebs Cycle"), NcertTopic("Electron Transport Chain"))),
            NcertChapter("Plant Growth and Development", listOf(NcertTopic("Plant Hormones"), NcertTopic("Photoperiodism"))),
            NcertChapter("Digestion and Absorption", listOf(NcertTopic("Digestive System"), NcertTopic("Digestive Enzymes"))),
            NcertChapter("Breathing and Exchange of Gases", listOf(NcertTopic("Respiratory System"), NcertTopic("Gas Exchange"))),
            NcertChapter("Body Fluids and Circulation", listOf(NcertTopic("Blood"), NcertTopic("Human Heart"))),
            NcertChapter("Excretory Products and Their Elimination", listOf(NcertTopic("Human Excretory System"), NcertTopic("Urine Formation"))),
            NcertChapter("Locomotion and Movement", listOf(NcertTopic("Muscles"), NcertTopic("Skeletal System"))),
            NcertChapter("Neural Control and Coordination", listOf(NcertTopic("Neurons"), NcertTopic("Human Brain"), NcertTopic("Reflex Action"))),
            NcertChapter("Chemical Coordination and Integration", listOf(NcertTopic("Endocrine Glands"), NcertTopic("Hormones"))),
        )),

        NcertSyllabus("Class 11", "Mathematics", listOf(
            NcertChapter("Sets", listOf(NcertTopic("Types of Sets"), NcertTopic("Operations on Sets"), NcertTopic("Venn Diagrams"))),
            NcertChapter("Relations and Functions", listOf(NcertTopic("Cartesian Product"), NcertTopic("Functions and Their Types"))),
            NcertChapter("Trigonometric Functions", listOf(NcertTopic("Trigonometric Ratios"), NcertTopic("Trigonometric Identities"), NcertTopic("Heights and Distances"))),
            NcertChapter("Principle of Mathematical Induction", listOf(NcertTopic("First Principle"), NcertTopic("Applications"))),
            NcertChapter("Complex Numbers and Quadratic Equations", listOf(NcertTopic("Algebra of Complex Numbers"), NcertTopic("Argand Plane"))),
            NcertChapter("Linear Inequalities", listOf(NcertTopic("Algebraic Solutions"), NcertTopic("Graphical Solutions"))),
            NcertChapter("Permutations and Combinations", listOf(NcertTopic("Factorial Notation"), NcertTopic("Permutations"), NcertTopic("Combinations"))),
            NcertChapter("Binomial Theorem", listOf(NcertTopic("General and Middle Term"), NcertTopic("Expansion"))),
            NcertChapter("Sequences and Series", listOf(NcertTopic("Arithmetic Progression"), NcertTopic("Geometric Progression"), NcertTopic("Sum of Special Series"))),
            NcertChapter("Straight Lines", listOf(NcertTopic("Slope of a Line"), NcertTopic("Various Forms of Line Equations"))),
            NcertChapter("Conic Sections", listOf(NcertTopic("Circle"), NcertTopic("Parabola"), NcertTopic("Ellipse"), NcertTopic("Hyperbola"))),
            NcertChapter("Introduction to Three Dimensional Geometry", listOf(NcertTopic("Coordinates in 3D"), NcertTopic("Distance and Section Formula"))),
            NcertChapter("Limits and Derivatives", listOf(NcertTopic("Limits"), NcertTopic("Derivatives"), NcertTopic("Algebra of Derivatives"))),
            NcertChapter("Mathematical Reasoning", listOf(NcertTopic("Statements"), NcertTopic("Implications"))),
            NcertChapter("Statistics", listOf(NcertTopic("Measures of Dispersion"), NcertTopic("Standard Deviation"))),
            NcertChapter("Probability", listOf(NcertTopic("Random Experiments"), NcertTopic("Axiomatic Approach"))),
        )),

        NcertSyllabus("Class 11", "Economics", listOf(
            NcertChapter("Indian Economy on the Eve of Independence", listOf(NcertTopic("Colonial Rule and Economy"), NcertTopic("Agriculture and Industry"))),
            NcertChapter("Indian Economy 1950-1990", listOf(NcertTopic("Planning"), NcertTopic("Agriculture and Industry Reforms"))),
            NcertChapter("Economic Reforms since 1991", listOf(NcertTopic("Liberalisation"), NcertTopic("Privatisation"), NcertTopic("Globalisation"))),
            NcertChapter("Human Capital Formation in India", listOf(NcertTopic("Education and Health"), NcertTopic("Human Capital vs Physical Capital"))),
            NcertChapter("Rural Development", listOf(NcertTopic("Credit and Marketing"), NcertTopic("Organic Farming"))),
            NcertChapter("Employment: Growth, Informalisation and Other Issues", listOf(NcertTopic("Types of Employment"), NcertTopic("Unemployment"))),
            NcertChapter("Environment and Sustainable Development", listOf(NcertTopic("Environmental Degradation"), NcertTopic("Sustainable Development"))),
            NcertChapter("Comparative Development Experiences of India and Its Neighbours", listOf(NcertTopic("India, China and Pakistan Comparison"))),
            NcertChapter("Statistics: Introduction", listOf(NcertTopic("Data Collection"), NcertTopic("Types of Data"))),
            NcertChapter("Collection of Data", listOf(NcertTopic("Census and Sample"), NcertTopic("Methods of Sampling"))),
            NcertChapter("Organisation of Data", listOf(NcertTopic("Classification"), NcertTopic("Frequency Distribution"))),
            NcertChapter("Presentation of Data", listOf(NcertTopic("Textual Presentation"), NcertTopic("Tabular Presentation"), NcertTopic("Diagrams and Graphs"))),
            NcertChapter("Measures of Central Tendency", listOf(NcertTopic("Mean, Median, Mode"))),
            NcertChapter("Measures of Dispersion", listOf(NcertTopic("Range, Quartile Deviation"), NcertTopic("Standard Deviation"))),
            NcertChapter("Correlation", listOf(NcertTopic("Karl Pearson's Coefficient"), NcertTopic("Spearman's Rank Correlation"))),
            NcertChapter("Index Numbers", listOf(NcertTopic("Construction of Index Numbers"), NcertTopic("Consumer Price Index"))),
        )),

        // ════ CLASS 12 ════
        NcertSyllabus("Class 12", "Physics", listOf(
            NcertChapter("Electric Charges and Fields", listOf(NcertTopic("Coulomb's Law"), NcertTopic("Electric Field and Flux"), NcertTopic("Gauss's Law"))),
            NcertChapter("Electrostatic Potential and Capacitance", listOf(NcertTopic("Electric Potential"), NcertTopic("Equipotential Surfaces"), NcertTopic("Capacitors"))),
            NcertChapter("Current Electricity", listOf(NcertTopic("Ohm's Law"), NcertTopic("Kirchhoff's Laws"), NcertTopic("Wheatstone Bridge"))),
            NcertChapter("Moving Charges and Magnetism", listOf(NcertTopic("Magnetic Force"), NcertTopic("Biot-Savart Law"), NcertTopic("Ampere's Circuital Law"))),
            NcertChapter("Magnetism and Matter", listOf(NcertTopic("Bar Magnet"), NcertTopic("Earth's Magnetism"), NcertTopic("Magnetic Properties"))),
            NcertChapter("Electromagnetic Induction", listOf(NcertTopic("Faraday's Law"), NcertTopic("Lenz's Law"), NcertTopic("Eddy Currents"))),
            NcertChapter("Alternating Current", listOf(NcertTopic("AC Voltage"), NcertTopic("LCR Circuit"), NcertTopic("Transformers"))),
            NcertChapter("Electromagnetic Waves", listOf(NcertTopic("Maxwell's Equations"), NcertTopic("Electromagnetic Spectrum"))),
            NcertChapter("Ray Optics and Optical Instruments", listOf(NcertTopic("Reflection and Refraction"), NcertTopic("Lenses"), NcertTopic("Microscope and Telescope"))),
            NcertChapter("Wave Optics", listOf(NcertTopic("Huygens' Principle"), NcertTopic("Interference"), NcertTopic("Diffraction"))),
            NcertChapter("Dual Nature of Radiation and Matter", listOf(NcertTopic("Photoelectric Effect"), NcertTopic("de Broglie Waves"))),
            NcertChapter("Atoms", listOf(NcertTopic("Rutherford's Model"), NcertTopic("Bohr's Model"), NcertTopic("Hydrogen Spectrum"))),
            NcertChapter("Nuclei", listOf(NcertTopic("Nuclear Force"), NcertTopic("Radioactivity"), NcertTopic("Nuclear Energy"))),
            NcertChapter("Semiconductor Electronics", listOf(NcertTopic("p-n Junction"), NcertTopic("Diodes"), NcertTopic("Logic Gates"))),
        )),

        NcertSyllabus("Class 12", "Chemistry", listOf(
            NcertChapter("The Solid State", listOf(NcertTopic("Crystal Lattice"), NcertTopic("Unit Cell"), NcertTopic("Types of Solids"))),
            NcertChapter("Solutions", listOf(NcertTopic("Concentration of Solutions"), NcertTopic("Raoult's Law"), NcertTopic("Colligative Properties"))),
            NcertChapter("Electrochemistry", listOf(NcertTopic("Electrochemical Cells"), NcertTopic("Nernst Equation"), NcertTopic("Electrolysis"))),
            NcertChapter("Chemical Kinetics", listOf(NcertTopic("Rate of Reaction"), NcertTopic("Order of Reaction"), NcertTopic("Arrhenius Equation"))),
            NcertChapter("Surface Chemistry", listOf(NcertTopic("Adsorption"), NcertTopic("Colloids"), NcertTopic("Catalysis"))),
            NcertChapter("Isolation of Elements", listOf(NcertTopic("Metallurgical Processes"), NcertTopic("Refining"))),
            NcertChapter("The p-Block Elements", listOf(NcertTopic("Group 15 Elements"), NcertTopic("Group 16 Elements"), NcertTopic("Group 17 Elements"), NcertTopic("Group 18 Elements"))),
            NcertChapter("The d and f-Block Elements", listOf(NcertTopic("Transition Metals"), NcertTopic("Lanthanides and Actinides"))),
            NcertChapter("Coordination Compounds", listOf(NcertTopic("Werner's Theory"), NcertTopic("Nomenclature"), NcertTopic("Isomerism"), NcertTopic("Bonding Theories"))),
            NcertChapter("Haloalkanes and Haloarenes", listOf(NcertTopic("Nomenclature"), NcertTopic("Reactions"), NcertTopic("Stereochemistry"))),
            NcertChapter("Alcohols, Phenols and Ethers", listOf(NcertTopic("Preparation and Properties"), NcertTopic("Reactions"))),
            NcertChapter("Aldehydes, Ketones and Carboxylic Acids", listOf(NcertTopic("Preparation"), NcertTopic("Reactions"), NcertTopic("Mechanisms"))),
            NcertChapter("Amines", listOf(NcertTopic("Classification"), NcertTopic("Preparation and Properties"))),
            NcertChapter("Biomolecules", listOf(NcertTopic("Carbohydrates"), NcertTopic("Proteins"), NcertTopic("Nucleic Acids"), NcertTopic("Vitamins"))),
            NcertChapter("Polymers", listOf(NcertTopic("Classification"), NcertTopic("Polymerisation"), NcertTopic("Biopolymers"))),
            NcertChapter("Chemistry in Everyday Life", listOf(NcertTopic("Drugs"), NcertTopic("Soaps and Detergents"), NcertTopic("Food Chemistry"))),
        )),

        NcertSyllabus("Class 12", "Biology", listOf(
            NcertChapter("Reproduction in Organisms", listOf(NcertTopic("Types of Reproduction"), NcertTopic("Sexual Reproduction"))),
            NcertChapter("Sexual Reproduction in Flowering Plants", listOf(NcertTopic("Flower Structure"), NcertTopic("Pollination and Fertilisation"), NcertTopic("Seed Development"))),
            NcertChapter("Human Reproduction", listOf(NcertTopic("Male and Female Reproductive Systems"), NcertTopic("Fertilisation and Implantation"), NcertTopic("Pregnancy and Parturition"))),
            NcertChapter("Reproductive Health", listOf(NcertTopic("Contraception"), NcertTopic("STDs"), NcertTopic("Assisted Reproductive Technologies"))),
            NcertChapter("Principles of Inheritance and Variation", listOf(NcertTopic("Mendel's Laws"), NcertTopic("Chromosomal Theory"), NcertTopic("Genetic Disorders"))),
            NcertChapter("Molecular Basis of Inheritance", listOf(NcertTopic("DNA Structure"), NcertTopic("Transcription and Translation"), NcertTopic("Human Genome Project"))),
            NcertChapter("Evolution", listOf(NcertTopic("Theories of Evolution"), NcertTopic("Evidences of Evolution"), NcertTopic("Hardy-Weinberg Principle"))),
            NcertChapter("Human Health and Disease", listOf(NcertTopic("Immunity"), NcertTopic("Diseases"), NcertTopic("Drug and Alcohol Abuse"))),
            NcertChapter("Strategies for Enhancement in Food Production", listOf(NcertTopic("Animal Husbandry"), NcertTopic("Plant Breeding"), NcertTopic("Tissue Culture"))),
            NcertChapter("Microbes in Human Welfare", listOf(NcertTopic("Microbes in Food"), NcertTopic("Antibiotics"), NcertTopic("Sewage Treatment"))),
            NcertChapter("Biotechnology: Principles and Processes", listOf(NcertTopic("Genetic Engineering"), NcertTopic("Recombinant DNA Technology"))),
            NcertChapter("Biotechnology and Its Applications", listOf(NcertTopic("Gene Therapy"), NcertTopic("Transgenic Animals"), NcertTopic("Biopiracy"))),
            NcertChapter("Organisms and Populations", listOf(NcertTopic("Habitat and Niche"), NcertTopic("Population Interactions"), NcertTopic("Population Attributes"))),
            NcertChapter("Ecosystem", listOf(NcertTopic("Energy Flow"), NcertTopic("Nutrient Cycling"), NcertTopic("Ecological Succession"))),
            NcertChapter("Biodiversity and Conservation", listOf(NcertTopic("Types of Biodiversity"), NcertTopic("Biodiversity Conservation"))),
            NcertChapter("Environmental Issues", listOf(NcertTopic("Pollution"), NcertTopic("Global Warming"), NcertTopic("Deforestation"))),
        )),

        NcertSyllabus("Class 12", "Mathematics", listOf(
            NcertChapter("Relations and Functions", listOf(NcertTopic("Types of Relations"), NcertTopic("Types of Functions"), NcertTopic("Composition of Functions"))),
            NcertChapter("Inverse Trigonometric Functions", listOf(NcertTopic("Properties of Inverse Functions"), NcertTopic("Graphs"))),
            NcertChapter("Matrices", listOf(NcertTopic("Types of Matrices"), NcertTopic("Operations on Matrices"), NcertTopic("Transpose and Inverse"))),
            NcertChapter("Determinants", listOf(NcertTopic("Properties of Determinants"), NcertTopic("Area of Triangle"), NcertTopic("Adjoint and Inverse"))),
            NcertChapter("Continuity and Differentiability", listOf(NcertTopic("Continuity"), NcertTopic("Differentiability"), NcertTopic("Mean Value Theorem"))),
            NcertChapter("Application of Derivatives", listOf(NcertTopic("Rate of Change"), NcertTopic("Maxima and Minima"), NcertTopic("Tangents and Normals"))),
            NcertChapter("Integrals", listOf(NcertTopic("Indefinite Integrals"), NcertTopic("Definite Integrals"), NcertTopic("Properties of Integrals"))),
            NcertChapter("Application of Integrals", listOf(NcertTopic("Area Under Curves"), NcertTopic("Area Between Two Curves"))),
            NcertChapter("Differential Equations", listOf(NcertTopic("Order and Degree"), NcertTopic("Solution Methods"), NcertTopic("Linear Differential Equations"))),
            NcertChapter("Vector Algebra", listOf(NcertTopic("Types of Vectors"), NcertTopic("Scalar and Vector Products"))),
            NcertChapter("Three Dimensional Geometry", listOf(NcertTopic("Direction Cosines"), NcertTopic("Line in Space"), NcertTopic("Plane"))),
            NcertChapter("Linear Programming", listOf(NcertTopic("Formulation of LPP"), NcertTopic("Graphical Solution"))),
            NcertChapter("Probability", listOf(NcertTopic("Conditional Probability"), NcertTopic("Bayes' Theorem"), NcertTopic("Random Variables"))),
        )),

        NcertSyllabus("Class 12", "Economics", listOf(
            NcertChapter("Introduction (Microeconomics)", listOf(NcertTopic("Central Problems of Economy"), NcertTopic("Production Possibility Frontier"))),
            NcertChapter("Theory of Consumer Behaviour", listOf(NcertTopic("Utility Analysis"), NcertTopic("Indifference Curve"), NcertTopic("Budget Line"))),
            NcertChapter("Production and Costs", listOf(NcertTopic("Production Function"), NcertTopic("Short and Long Run Costs"))),
            NcertChapter("The Theory of the Firm Under Perfect Competition", listOf(NcertTopic("Revenue and Profit"), NcertTopic("Supply Curve"))),
            NcertChapter("Market Equilibrium", listOf(NcertTopic("Equilibrium Price"), NcertTopic("Effects of Shifts"))),
            NcertChapter("Non-Competitive Markets", listOf(NcertTopic("Monopoly"), NcertTopic("Monopolistic Competition"))),
            NcertChapter("Introduction to Macroeconomics", listOf(NcertTopic("Circular Flow of Income"), NcertTopic("National Income Accounting"))),
            NcertChapter("National Income Accounting", listOf(NcertTopic("GDP and GNP"), NcertTopic("Methods of Calculation"))),
            NcertChapter("Money and Banking", listOf(NcertTopic("Functions of Money"), NcertTopic("Money Supply"), NcertTopic("Central Bank"))),
            NcertChapter("Income Determination", listOf(NcertTopic("Aggregate Demand"), NcertTopic("Multiplier"))),
            NcertChapter("Government Budget and the Economy", listOf(NcertTopic("Components of Budget"), NcertTopic("Fiscal Policy"))),
            NcertChapter("Balance of Payments", listOf(NcertTopic("Components of BOP"), NcertTopic("Exchange Rate"))),
        )),

        NcertSyllabus("Class 12", "Business Studies", listOf(
            NcertChapter("Nature and Significance of Management", listOf(NcertTopic("Management as Profession"), NcertTopic("Levels of Management"))),
            NcertChapter("Principles of Management", listOf(NcertTopic("Fayol's Principles"), NcertTopic("Taylor's Scientific Management"))),
            NcertChapter("Business Environment", listOf(NcertTopic("Economic and Non-economic Environment"), NcertTopic("Liberalisation and Globalisation"))),
            NcertChapter("Planning", listOf(NcertTopic("Planning Process"), NcertTopic("Types of Plans"))),
            NcertChapter("Organising", listOf(NcertTopic("Organisational Structure"), NcertTopic("Delegation and Decentralisation"))),
            NcertChapter("Staffing", listOf(NcertTopic("Recruitment"), NcertTopic("Selection and Training"))),
            NcertChapter("Directing", listOf(NcertTopic("Supervision"), NcertTopic("Motivation"), NcertTopic("Leadership"))),
            NcertChapter("Controlling", listOf(NcertTopic("Controlling Process"), NcertTopic("Techniques of Control"))),
            NcertChapter("Financial Management", listOf(NcertTopic("Financial Planning"), NcertTopic("Capital Structure"))),
            NcertChapter("Financial Markets", listOf(NcertTopic("Money Market"), NcertTopic("Capital Market"), NcertTopic("SEBI"))),
            NcertChapter("Marketing", listOf(NcertTopic("Marketing Mix"), NcertTopic("Product and Pricing"))),
            NcertChapter("Consumer Protection", listOf(NcertTopic("Consumer Rights"), NcertTopic("Consumer Forums"))),
        )),

        NcertSyllabus("Class 12", "Accountancy", listOf(
            NcertChapter("Accounting for Non-profit Organisations", listOf(NcertTopic("Receipts and Payments Account"), NcertTopic("Income and Expenditure Account"), NcertTopic("Balance Sheet"))),
            NcertChapter("Accounting for Partnership Firms - Basics", listOf(NcertTopic("Partnership Deed"), NcertTopic("Profit Sharing Ratio"), NcertTopic("Capital Accounts"))),
            NcertChapter("Reconstitution of a Partnership Firm - Admission of a Partner", listOf(NcertTopic("New Profit Sharing Ratio"), NcertTopic("Goodwill"), NcertTopic("Revaluation of Assets and Liabilities"))),
            NcertChapter("Reconstitution of a Partnership Firm - Retirement/Death of a Partner", listOf(NcertTopic("Gaining Ratio"), NcertTopic("Settlement of Amount"))),
            NcertChapter("Dissolution of Partnership Firm", listOf(NcertTopic("Realisation Account"), NcertTopic("Settlement of Accounts"))),
            NcertChapter("Accounting for Share Capital", listOf(NcertTopic("Issue of Shares"), NcertTopic("Forfeiture and Re-issue"))),
            NcertChapter("Issue and Redemption of Debentures", listOf(NcertTopic("Types of Debentures"), NcertTopic("Redemption Methods"))),
            NcertChapter("Financial Statements of a Company", listOf(NcertTopic("Balance Sheet"), NcertTopic("Statement of Profit and Loss"))),
            NcertChapter("Analysis of Financial Statements", listOf(NcertTopic("Comparative Statements"), NcertTopic("Common Size Statements"))),
            NcertChapter("Accounting Ratios", listOf(NcertTopic("Liquidity Ratios"), NcertTopic("Solvency Ratios"), NcertTopic("Profitability Ratios"))),
            NcertChapter("Cash Flow Statement", listOf(NcertTopic("Operating Activities"), NcertTopic("Investing Activities"), NcertTopic("Financing Activities"))),
        )),
    )
}
