-- =============================================================================
-- Migration: setup_skill_test_schema
-- Subject:   Skill Test System — AI-generated weekly MCQ tests for children
--            linked by parents. 4 tables + 1 badge definition + remove
--            hardcoded app_config badges.
--
-- WHY THIS EXISTS
--   When a parent links their child for the first time, the child gets access
--   to a weekly skill test. 100+ MCQ questions are generated by AI (Mistral /
--   Gemini / NVIDIA — non-PII content, so training-opt-in providers are fine)
--   and stored in the DB. The child takes the test, gets instant evaluation,
--   and the best score is preserved across attempts. Scoring 60+ awards the
--   first badge. New questions are generated weekly; old ones are purged.
--   The child can retake the test 7 days after their last attempt.
--
-- HOW TO RUN
--   Supabase -> SQL Editor -> paste this whole file -> Run.
--   100% SAFE TO RE-RUN: every CREATE TABLE uses IF NOT EXISTS, every
--   INSERT uses ON CONFLICT DO NOTHING, every DROP/DELETE is targeted.
--
-- TABLES CREATED
--   1. skill_test_questions   — pool of 100+ AI-generated MCQs per grade
--   2. skill_test_attempts    — each test attempt by a child
--   3. skill_test_answers     — per-question answers for instant evaluation
--   4. skill_test_best_scores — best score per child (best of all attempts)
--
-- BADGE INSERTED
--   game_badge_definitions: code='skill_test_first_pass' — awarded at 60+ score
--
-- CONFIG REMOVED
--   app_config row 'parent_track_badges' is deleted — badges now come from
--   the gamification system (game_student_badges) driven by real data.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- 1. skill_test_questions — AI-generated MCQ pool, refreshed weekly
-- =============================================================================
CREATE TABLE IF NOT EXISTS skill_test_questions (
    id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    batch_id        UUID        NOT NULL,                          -- identifies the weekly batch
    grade_level     VARCHAR(32) NOT NULL,                          -- e.g. "Grade 1", "Grade 3"
    subject         VARCHAR(64) NOT NULL,                          -- e.g. "Math", "English", "Science", "GK"
    question_text   TEXT        NOT NULL,
    options         TEXT        NOT NULL DEFAULT '[]',             -- JSON array: ["A) ...", "B) ...", "C) ...", "D) ..."]
    correct_answer  VARCHAR(8)  NOT NULL,                          -- "A" | "B" | "C" | "D"
    explanation     TEXT        NOT NULL DEFAULT '',
    difficulty      VARCHAR(8)  NOT NULL DEFAULT 'medium',         -- easy | medium | hard
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,             -- false = archived (pending purge)
    ai_provider     VARCHAR(32) NULL,                              -- which AI generated this (mistral/gemini/nvidia)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_stq_batch       ON skill_test_questions (batch_id);
CREATE INDEX IF NOT EXISTS ix_stq_grade       ON skill_test_questions (grade_level, is_active);
CREATE INDEX IF NOT EXISTS ix_stq_batch_grade ON skill_test_questions (batch_id, grade_level, is_active);
CREATE INDEX IF NOT EXISTS ix_stq_active      ON skill_test_questions (is_active, created_at);

-- =============================================================================
-- 2. skill_test_attempts — each test attempt by a child
-- =============================================================================
CREATE TABLE IF NOT EXISTS skill_test_attempts (
    id                 UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    child_id           UUID        NOT NULL,                        -- FK children.id
    parent_id          UUID        NOT NULL,                        -- FK app_users.id (who initiated)
    school_id          UUID        NULL,                            -- FK schools.id (optional)
    batch_id           UUID        NOT NULL,                        -- which question batch
    grade_level        VARCHAR(32) NOT NULL,                        -- grade at time of attempt
    total_questions    INTEGER     NOT NULL DEFAULT 0,
    correct_count      INTEGER     NOT NULL DEFAULT 0,
    score_percentage   INTEGER     NOT NULL DEFAULT 0,              -- 0-100
    status             VARCHAR(16) NOT NULL DEFAULT 'in_progress',  -- in_progress | completed
    started_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at       TIMESTAMPTZ NULL,
    next_eligible_at   TIMESTAMPTZ NULL,                            -- completed_at + 7 days (for retake lock)
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_sta_child       ON skill_test_attempts (child_id);
CREATE INDEX IF NOT EXISTS ix_sta_child_status ON skill_test_attempts (child_id, status);
CREATE INDEX IF NOT EXISTS ix_sta_parent      ON skill_test_attempts (parent_id);
CREATE INDEX IF NOT EXISTS ix_sta_next_eligible ON skill_test_attempts (child_id, next_eligible_at);

-- =============================================================================
-- 3. skill_test_answers — per-question answers for instant evaluation
-- =============================================================================
CREATE TABLE IF NOT EXISTS skill_test_answers (
    id               UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    attempt_id       UUID        NOT NULL,                          -- FK skill_test_attempts.id
    question_id      UUID        NOT NULL,                          -- FK skill_test_questions.id
    selected_answer  VARCHAR(8)  NOT NULL,                          -- "A" | "B" | "C" | "D"
    is_correct       BOOLEAN     NOT NULL DEFAULT FALSE,
    answered_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_stans_attempt  ON skill_test_answers (attempt_id);
CREATE INDEX IF NOT EXISTS ix_stans_question ON skill_test_answers (question_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_stans_attempt_question ON skill_test_answers (attempt_id, question_id);

-- =============================================================================
-- 4. skill_test_best_scores — best score per child (best of all attempts)
-- =============================================================================
CREATE TABLE IF NOT EXISTS skill_test_best_scores (
    id                UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    child_id          UUID        NOT NULL UNIQUE,                  -- one row per child
    best_score        INTEGER     NOT NULL DEFAULT 0,               -- 0-100
    best_attempt_id   UUID        NULL,                             -- FK skill_test_attempts.id
    attempts_count    INTEGER     NOT NULL DEFAULT 0,
    badge_earned      BOOLEAN     NOT NULL DEFAULT FALSE,           -- true once 60+ scored
    last_attempt_at   TIMESTAMPTZ NULL,
    next_eligible_at  TIMESTAMPTZ NULL,                             -- when can retake (last_attempt + 7 days)
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_stbs_child      ON skill_test_best_scores (child_id);
CREATE INDEX IF NOT EXISTS ix_stbs_badge      ON skill_test_best_scores (badge_earned);

-- =============================================================================
-- 5. Badge definition — "First Step" badge for scoring 60+ on skill test
--    Inserted into game_badge_definitions so the existing BadgeCriteriaEvaluator
--    and GamificationService can manage it. Criteria type = "skill_test_pass"
--    (new type, evaluated in SkillTestService after test completion).
-- =============================================================================
INSERT INTO game_badge_definitions (
    id, school_id, code, name, description, icon_name,
    category, rarity, xp_requirement, criteria_json,
    is_active, is_seasonal, available_from, available_until, created_at
) VALUES (
    uuid_generate_v4(),
    NULL,                                   -- global badge (all schools)
    'skill_test_first_pass',
    'First Step',
    'Awarded for scoring 60% or above on your first skill test. The beginning of your learning journey!',
    'workspace_premium',
    'ACADEMIC',
    'COMMON',
    0,                                      -- no XP prerequisite; earned by action
    '{"type":"skill_test_pass","min_score":60}',
    TRUE,
    FALSE,
    NULL,
    NULL,
    now()
) ON CONFLICT (code) DO NOTHING;

-- =============================================================================
-- 6. Remove hardcoded parent_track_badges from app_config
--    Badges now come from game_student_badges (real, earned, per-child).
--    The TrackProgressRouting endpoint will read from game_student_badges
--    instead of the static CMS config.
-- =============================================================================
DELETE FROM app_config WHERE key = 'parent_track_badges';

-- =============================================================================
-- VERIFICATION QUERIES (safe to run, read-only)
-- =============================================================================
SELECT 'skill_test_questions' AS table_name, COUNT(*) AS row_count FROM skill_test_questions
UNION ALL
SELECT 'skill_test_attempts', COUNT(*) FROM skill_test_attempts
UNION ALL
SELECT 'skill_test_answers', COUNT(*) FROM skill_test_answers
UNION ALL
SELECT 'skill_test_best_scores', COUNT(*) FROM skill_test_best_scores;

SELECT code, name, criteria_json, is_active
FROM game_badge_definitions
WHERE code = 'skill_test_first_pass';

SELECT key FROM app_config WHERE key = 'parent_track_badges';
-- Expected: 0 rows (deleted above)
