import {
  IconAnnounce,
  IconAttendance,
  IconDashboard,
  IconFees,
  IconLeave,
  IconMarks,
  IconPeople,
  IconSettings,
  IconBolt,
  IconAlumni,
  IconShield,
  IconBook,
  IconReport,
  IconLanguage,
  IconLogs,
  IconTransport,
  IconLibrary,
  IconScholarship,
  IconSchedule,
  IconClasses,
  IconHealth,
  IconIdCard,
  IconEvent,
  IconAdmissions,
  IconLink,
  IconBranding,
  IconCalendarPlatform,
  IconPtm,
  IconPace,
  IconMessage,
  IconTrophy,
  IconExport,
} from "@/components/admin/icons";

export interface NavItem {
  href: string;
  label: string;
  icon: (p: { className?: string }) => JSX.Element;
  superAdminOnly?: boolean;
}

/** Single source of truth for the admin sidebar + route map. */
export const ADMIN_NAV: NavItem[] = [
  { href: "/admin/dashboard", label: "Dashboard", icon: IconDashboard },
  { href: "/admin/people", label: "People", icon: IconPeople },
  { href: "/admin/alumni", label: "Alumni", icon: IconAlumni },
  { href: "/admin/attendance", label: "Attendance", icon: IconAttendance },
  { href: "/admin/early-warning", label: "Early Warning", icon: IconShield },
  { href: "/admin/report-card", label: "Report Cards", icon: IconReport },
  { href: "/admin/tutor", label: "AI Tutor", icon: IconBook },
  { href: "/admin/marks", label: "Marks", icon: IconMarks },
  { href: "/admin/fees", label: "Fees", icon: IconFees },
  { href: "/admin/announcements", label: "Announcements", icon: IconAnnounce },
  { href: "/admin/leave", label: "Leave", icon: IconLeave },
  { href: "/admin/messages", label: "Messages", icon: IconMessage },
  { href: "/admin/scheduled-messages", label: "Scheduled Msgs", icon: IconSchedule },
  { href: "/admin/classes", label: "Classes & Subjects", icon: IconClasses },
  { href: "/admin/calendar", label: "Calendar", icon: IconCalendarPlatform },
  { href: "/admin/events", label: "Event Registration", icon: IconEvent },
  { href: "/admin/ptm", label: "PTM Scheduling", icon: IconPtm },
  { href: "/admin/scholarships", label: "Scholarships", icon: IconScholarship },
  { href: "/admin/library", label: "Library", icon: IconLibrary },
  { href: "/admin/transport", label: "Transport", icon: IconTransport },
  { href: "/admin/health-records", label: "Health Records", icon: IconHealth },
  { href: "/admin/id-cards", label: "ID Cards", icon: IconIdCard },
  { href: "/admin/admissions", label: "Admissions CRM", icon: IconAdmissions },
  { href: "/admin/link-requests", label: "Link Requests", icon: IconLink },
  { href: "/admin/branding", label: "Branding Kit", icon: IconBranding },
  { href: "/admin/pace-alerts", label: "Pace Alerts", icon: IconPace },
  { href: "/admin/gamification", label: "Gamification", icon: IconTrophy },
  { href: "/admin/records", label: "Records & Exports", icon: IconExport },
  { href: "/admin/settings", label: "Settings", icon: IconSettings },
  { href: "/admin/language", label: "Language", icon: IconLanguage, superAdminOnly: true },
  { href: "/admin/academics", label: "Academics", icon: IconBook },
  { href: "/admin/dev-tools", label: "Dev Tools", icon: IconBolt, superAdminOnly: true },
  { href: "/admin/logs", label: "Server Logs", icon: IconLogs, superAdminOnly: true },
];
